project:
  type: website
  output-dir: docs

execute:
    freeze: auto

website:
  title: "Motion Metrics"
  navbar:
    logo: img/MotionMetricsWhiteNobg.png
    background: primary
    right:
      - href: news.qmd
        text: News
      - href: services.qmd
        text: Services
      - href: people.qmd
        text: People
      - href: publications.qmd
        text: Publications
      - href: contact.qmd
        text: Contact
  page-footer: "Copyright 2023 &copy; Motion Metrics"
  # google-analytics: "G-K5TXS64QLN"
  # site-url: https://affcom.ku.edu
  repo-url: https://github.com/MotionMetricsLab


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    logo: MotionMetricsMain.png
    main_color: "#00c3b3"
